# Permalinks
permalink:           none

# Setup
title:               Nandu Rajagopala
tagline:             Solving company and customer problems
url:                 https://nandu306.github.io/
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nandu Rajagopala
  url:
  email:             nandu.rajagopala@cantab.net

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/nandu306
google_analytics:    G-NKLM3WSGRC
twitter:
github:              Nandu306
linkedin:            nandurajagopala
medium:              nandurajagopala

# Gems
plugins:
  - jekyll-paginate
  # - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# collections:
#   articles:
#     output: true
#     permalink: /articles/:path
