# Permalinks
permalink:           none

# Setup
title:               Nandu Rajagopala
tagline:             Product Manager | Ruby on Rails Developer in Berlin
url:                 https://nandu306.github.io/
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Nandu Rajagopala
  url:
  email:             nandu.rajagopala@cantab.net

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/nandu306
google_analytics:    G-NKLM3WSGRC
twitter:
github:              Nandu306
linkedin:            nandurajagopala
medium:              nandurajagopala

# Gems
plugins:
  - jekyll-paginate
  # - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# collections:
#   articles:
#     output: true
#     permalink: /articles/:path

# Compress images

name: Optimize Images

on:
  pull_request:
    paths:
      - "**.jpg"
      - "**.jpeg"
      - "**.png"
      - "**.webp"

jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository

    name: calibreapp/image-actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: $
